#pragma checksum "MainWindow.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "0619BFD723AD3EE59249E5AA68BACB2CCC9C0C4558B4D9AA1C10BA6EA64F346D"
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using Tekla.Structures.Dialog;
using Tekla.Structures.Dialog.UIControls;
using WPFPluginTemplate;


namespace WPFPluginTemplate {
    
    
    /// <summary>
    /// MainWindow
    /// </summary>
    public partial class MainWindow : Tekla.Structures.Dialog.PluginWindowBase, System.Windows.Markup.IComponentConnector {
        
        
        #line 24 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox zazor;
        
        #line default
        #line hidden
        
        
        #line 33 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox faska;
        
        #line default
        #line hidden
        
        
        #line 57 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox H1_transition;
        
        #line default
        #line hidden
        
        
        #line 59 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox transition;
        
        #line default
        #line hidden
        
        
        #line 105 "MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox L1_transition;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/WPFPluginTemplate;component/mainwindow.xaml", System.UriKind.Relative);
            
            #line 1 "MainWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 18 "MainWindow.xaml"
            ((Tekla.Structures.Dialog.UIControls.WpfOkApplyModifyGetOnOffCancel)(target)).ApplyClicked += new System.EventHandler(this.WpfOkApplyModifyGetOnOffCancel_ApplyClicked);
            
            #line default
            #line hidden
            
            #line 18 "MainWindow.xaml"
            ((Tekla.Structures.Dialog.UIControls.WpfOkApplyModifyGetOnOffCancel)(target)).CancelClicked += new System.EventHandler(this.WpfOkApplyModifyGetOnOffCancel_CancelClicked);
            
            #line default
            #line hidden
            
            #line 18 "MainWindow.xaml"
            ((Tekla.Structures.Dialog.UIControls.WpfOkApplyModifyGetOnOffCancel)(target)).GetClicked += new System.EventHandler(this.WpfOkApplyModifyGetOnOffCancel_GetClicked);
            
            #line default
            #line hidden
            
            #line 18 "MainWindow.xaml"
            ((Tekla.Structures.Dialog.UIControls.WpfOkApplyModifyGetOnOffCancel)(target)).ModifyClicked += new System.EventHandler(this.WpfOkApplyModifyGetOnOffCancel_ModifyClicked);
            
            #line default
            #line hidden
            
            #line 18 "MainWindow.xaml"
            ((Tekla.Structures.Dialog.UIControls.WpfOkApplyModifyGetOnOffCancel)(target)).OkClicked += new System.EventHandler(this.WpfOkApplyModifyGetOnOffCancel_OkClicked);
            
            #line default
            #line hidden
            
            #line 18 "MainWindow.xaml"
            ((Tekla.Structures.Dialog.UIControls.WpfOkApplyModifyGetOnOffCancel)(target)).OnOffClicked += new System.EventHandler(this.WpfOkApplyModifyGetOnOffCancel_OnOffClicked);
            
            #line default
            #line hidden
            return;
            case 2:
            this.zazor = ((System.Windows.Controls.TextBox)(target));
            return;
            case 3:
            this.faska = ((System.Windows.Controls.ComboBox)(target));
            
            #line 33 "MainWindow.xaml"
            this.faska.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.ComboBox_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 4:
            this.H1_transition = ((System.Windows.Controls.TextBox)(target));
            return;
            case 5:
            this.transition = ((System.Windows.Controls.ComboBox)(target));
            
            #line 59 "MainWindow.xaml"
            this.transition.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.transition_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 6:
            this.L1_transition = ((System.Windows.Controls.TextBox)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

